### ISSUE TITLE
Issue passing in crypto.properties location when file not hosted in classpath

### ISSUE THREAD

**Issue by AlexandruCiobanu** [phax/ph-commons#22]
Hi Phil,

Do you have any idea how might I be able to pass in crypto.properties path via a systemproperty? 
I also tried setting a config.properties file - with all the entries from crypto.properties -  referenced via config.file SystemProperty but without success.

**Comment by AlexandruCiobanu** [comment]
Nevermind, I found it :)

**Comment by phax** [comment]
Great thanks :) If you need help in upgrading the as4 solution, just ping me by email
