### ISSUE TITLE
Cut a release please

### ISSUE THREAD

**Issue by cemo** [phax/ph-commons#32]
I had used 11.0.0 version of https://github.com/phax/ph-commons project for https://github.com/phax/ph-schematron but it had missing one method.

com.helger.xml.XMLHelper#pathToNodeBuilder seems missing in v11.0.0 and I build on my box today it. After it https://github.com/phax/ph-schematron was successfully built without tests.

**Comment by cemo** [comment]
ph-commons 11.0.1-SNAPSHOT has a failing test

**Comment by phax** [comment]
When running in JDK 18 - noted and confirmed

**Comment by phax** [comment]
Fixed in 11.0.1 release
