### ISSUE TITLE
Invoice XML Format generate only a line

### ISSUE THREAD

**Issue by miika3l** [phax/ph-commons#7]
Hi Philip, invoices generated with the JAXBWriterBuilder class are not formatted (the XML data isn't formatted with linefeeds and indentation). I think the property `Marshaller.JAXB_FORMATTED_OUTPUT` is not set up.

`final ESuccess eSuccess = UBL20Writer.invoice ().write (aInvoice, new File ("target/dummy-invoice.xml"));`

**Updated:**
Sorry, it was  my mistake. For fix, is necessary use line below:

`final ESuccess eSuccess = UBL20Writer.invoice().setFormattedOutput(true).write(aInvoice, new File("target/dummy-invoice-with-ext.xml"));`

regards!

**Comment by phax** [comment]
Exactly - Glad you solved it :)
